### ISSUE TITLE
Strange behaviour with latest excel file from Fineco

### ISSUE THREAD

**Issue by elcoda** [frankIT/ofxstatement-fineco#3]
Dears,
I found two bugs using ofxstatement-fineco with latest version of Excel file downloaded from Fineco.

## Fineco.py line 76

row[0] is a float number, but we use startswith(...) so I changed the if statement adding a str(row[0]) in:

`  if self.th_separator_idx > 0:
                if row[0] != '' and not str(row[0]).startswith(self.common_footer_marker):`

## Fineco.py last few lines

In the original .py stmt_line.date was computed with:

`stmt_line.date = datetime.strptime(row[0], self.date_format)`

but row[0] is a float number, but it is a number (Excel serial date).
So I created this method before:

```
 def xls_date(self,excel_serial_date):
        excel_date = int(excel_serial_date)
        dt = datetime.fromordinal(datetime(1900, 1, 1).toordinal() + excel_date - 2)
        tt = dt.timetuple()
        return dt
```

and then computed stmt_line.date in this way:

`stmt_line.date = self.xls_date(int(row[0]))`

Now it's working.
My fineco.py attached.

Ivan

[fineco.py.zip](https://github.com/frankIT/ofxstatement-fineco/files/3113046/fineco.py.zip)

**Comment by frankIT** [comment]
Hi @elcoda, thanks for your fix and sorry to hit you back after a decade, i totally forgot about this.
It looks like Fineco changed the data type for the cells containing the dates, so what was expected to be a string became a float.
I tested your code and it works so I'm going to accept the pull req from @MarcoBuster now, but I'll come back to this cause I'd like to make it backward compatible with the old statement files and I'd rather use `xlrd.xldate.xldate_as_tuple(xldate, datemode)`

Cheers :+1:
